name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run configure script
      run: ./path/to/configure  # Update the path if necessary
    - name: Build
      run: make
